name: Build Server

on:
  push:
    branches:
      - main
    paths:
      - 'packages/server/**'
      - '.yarnrc.yml'
      - '.github/workflows/build-server.yml'

jobs:
  server:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Push code to another branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: server-build # The branch name where you want to push the assets
          FOLDER: packages/server # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: 'Build: ({sha}) {msg}' # The commit message
