name: issue-new-branch

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v1

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: view issue information
        run: |
          echo "Entire Issue: ${{ github.event.issue.id }}"
      
      - name: create new branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: feature-${{ github.event.issue.id }}
